### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by andrew40** [roots/wp-stage-switcher#10]
On initial composer update with plugin as required in composer.json

`"require": {
    "php": ">=5.6",
    "composer/installers": "~1.0.12",
    "vlucas/phpdotenv": "^2.0.1",
    "johnpbloch/wordpress": "4.6.1",
    "oscarotero/env": "^1.0",
    "roots/wp-password-bcrypt": "1.0.0",
    "wpackagist-plugin/contact-form-7": "dev-trunk",
    "wpackagist-plugin/getty-images": "dev-trunk",
    "roots/wp-stage-switcher": "2.0.0",
    "roots/soil": "3.7.1"`

I am using and have setup Trellis/Bedrock. Line 53 states an issue between the stages but as I understand Bedrock already has WP_ENV; defined?

( ! ) Warning: Invalid argument supplied for foreach() in /srv/www/thefootballfamily.com/current/web/app/plugins/wp-stage-switcher/wp-stage-switcher.php on line 53
Call Stack
#	Time	Memory	Function	Location
1	0.0009	468976	{main}( )	.../plugins.php:0
2	0.2273	20106184	require_once( '/srv/www/thefootballfamily.com/current/web/wp/wp-admin/admin-header.php' )	.../plugins.php:408
3	0.2398	20186528	do_action( )	.../admin-header.php:214
4	0.2398	20186928	wp_admin_bar_render( )	.../plugin.php:524
5	0.2398	20187304	do_action_ref_array( )	.../admin-bar.php:83
6	0.2412	20193816	Roots\StageSwitcher\StageSwitcher->admin_bar_stage_switcher( )	.../plugin.php:600

**Comment by andrew40** [comment]
Think I have sorted it, I thought all this was configured as I was using Bedrock.

I have copied out the commented $env in wp-stage-switcher.php 

`$envs = [
'development' => 'http:/example.dev',
'staging'     => 'http://example-staging.com',
'production'  => 'http://example.com'
];
define('ENVIRONMENTS', serialize($envs));`

As an aside to save this being overwritten on an update, can we not define this in application.php within Bedrock?

**Comment by retlehs** [comment]
> I thought all this was configured as I was using Bedrock.

bedrock only has `WP_ENV`, not `ENVIRONMENTS` as mentioned in https://github.com/roots/wp-stage-switcher#requirements

you're asking whether or not you can place `ENVIRONMENTS` in `application.php`? yes, you can

please don't use github issues for support, use https://discourse.roots.io/

**Comment by andrew40** [comment]
told!
