### ISSUE TITLE
undefined constant

### ISSUE THREAD

**Issue by maciejjankowski** [roots/wp-stage-switcher#11]
Notice: Use of undefined constant ENVIRONMENTS - assumed 'ENVIRONMENTS' in /public_html/bedrock/web/app/plugins/wp-stage-switcher-2.0.0/wp-stage-switcher.php on line 50 Notice: unserialize(): Error at offset 0 of 12 bytes in /public_html/bedrock/web/app/plugins/wp-stage-switcher-2.0.0/wp-stage-switcher.php on line 50 Warning: Invalid argument supplied for foreach() in /public_html/bedrock/web/app/plugins/wp-stage-switcher-2.0.0/wp-stage-switcher.php on line 53

**Comment by retlehs** [comment]
you skipped the installation instructions

https://github.com/roots/wp-stage-switcher#requirements
