### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by swissspidy** [roots/wp-stage-switcher#19]
There have been a few enhancements and bug fixes in the past that I think warrant a new release. Plus, there are 3 pull requests that are currently open that could be considered as well.

It would be really great if a new version could be tagged after these get in as well.

Please let me know if I can help with a changelog or something.

**Comment by swalkinshaw** [comment]
I think we should do a minor version bump for master right now. And then we can bump to PHP 7 next as well and get rid of `maybe_unserialize`? (and maybe even `wp_parse_url`). That would be a major version.

**Comment by grappler** [comment]
@swalkinshaw Do you need any help with releasing a minor version?

**Comment by swalkinshaw** [comment]
Sorry @grappler missed this during vacation. If you want, we need to bump the version number in a few places + update CHANGELOG before we tag a release.

Let's do 2.1?
