### ISSUE TITLE
Bug: Multisite URL Rewriting Not Functional

### ISSUE THREAD

**Issue by dotsam** [roots/wp-stage-switcher#24]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Subdomain-based multisite URLs aren't modified in any helpful way. The full current URL host-part is replaced by the stage's host-part, with no attempt made to preserve the blog's domain.

#### What have you tried?
Configured the `ENVIRONMENTS` array with the URLs of the "main site" or just the domain suffix.

#### What insights have you gained?
When originally implemented in https://github.com/roots/wp-stage-switcher/commit/890a7111273e553dcfda9329f57261dac331e1af, the host was split on the assumption that the subdomain would be only a single level, which worked in most cases, but not all. When rewritten in #7, Purl was used for its `registerableDomain` property to attempt to determine the base domain portion which should be replaced and the subdomain which should be kept. Finally, in #18, the Purl dependancy was removed, but the `multisite_url` method was simplified too much and all logic about trying to determine subdomain and base domain was removed.

#### Possible solutions
Without involving external dependancies (and even then, a solution may not be available for every possible outcome), determining with certainty the sub domain/base domain portion of a multisite URL is difficult. I propose moving back to a solution similar to the original in https://github.com/roots/wp-stage-switcher/commit/890a7111273e553dcfda9329f57261dac331e1af but also providing a filter to allow for domain structures that don't fit.

#### Temporary workarounds
The `ENVIRONMENTS` array can be defined in a `sunrise.php` drop-in once the multisite domain has been resolved, but this still presents an issue where URL scheme might be changed based on the scheme of the current stage (ie. a production site using the https scheme would overwrite an http scheme for a development URL creating a broken link).

### Steps To Reproduce

1. Set up a subdomain-based multisite installation in 2 or more environments
1. Configure the `ENVIRONMENTS` array with URLs for these environments

### Expected Behavior

Subdomain portions of the environment URL will be maintained while base environment domains are replaced

### Actual Behavior

The entire subdomain URL is replaced with the URL from the `ENVIRONMENTS` array, discarding the subdomain

### Versions

2.1.1

**Comment by swalkinshaw** [comment]
>  I propose moving back to a solution similar to the original in 890a711 but also providing a filter to allow for domain structures that don't fit.

Seems reasonable to me 👍 

Would you like to do the change?

**Comment by dotsam** [comment]
> Would you like to do the change?

Yeah, I'll try and take a look at this next week.

Thinking through this a little more, the solution I might go after is to treat the URLs provided in the `ENVIRONMENTS` array as a domain suffix/base domain rather than a complete domain. A little opaque from a usage/discoverability standpoint, but it probably allows for the greatest flexibility.
