### ISSUE TITLE
Make it un-ignorably obvious when you're editing a non-canonical environment

### ISSUE THREAD

**Issue by MatthewEppelsheimer** [roots/wp-stage-switcher#5]
Here's an enhancement idea, that I'm willing to write code for, but want to get a :+1: from project owners first. I could see this idea being judged as an entirely separate plugin, but for me it is the feature that's missing to make this really great. Please let me know if you see it as a good fit.

There would be two steps to this: 

1) Extend the `ENVIRONMENT` constant to optionally support meta data through nested arrays. Strings will still work, but you could now do something like this:
```php
$envs = array(
  'development' => array(
    'url' => 'http://example.dev',
    'canonical' => false
  ),
  'staging'     => array(
    'url' => 'http://staging.example.com',
    'canonical' => false
  ),
  'production'  => 'http://example.com'
);
define('ENVIRONMENTS', serialize($envs));
```
2) If the environment is not canonical, add an Admin notice with filterable text that conveys essentially "whoa be super careful!", and change the color of the admin bar to something eye catching, like bright red or orange. 

The color, too, should probably be filterable. And since a user's admin color scheme is dynamic, this will need to account for that somehow — that bit will take some research.

**Comment by swalkinshaw** [comment]
Isn't the canonical URL always going to be `production`? If so you can just check for that to add your notices (which is a good idea btw).

**Comment by MatthewEppelsheimer** [comment]
In most cases yes, but not necessarily.

There are times when we're treating staging (or yet another instance) as
canonical, to stage content edit work before migrating it over to
production, especially during early phases of a site build.

So, which instance is canonical changes regularly throughout our workflows.
In fact it's those transition points that throw people off. This is why we
need this kind of obvious reminder, to help people remember when it has
changed.

On Tue, Sep 29, 2015 at 8:39 AM, Scott Walkinshaw <notifications@github.com>
wrote:

> Isn't the canonical URL always going to be production? If so you can just
> check for that to add your notices (which is a good idea btw).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roots/wp-stage-switcher/issues/5#issuecomment-144097266>
> .
>



-- 

Matthew Eppelsheimer
Rocket Lift

(503) 928-3478
matthew@rocketlift.com

I write a newsletter where I share the best articles and podcasts I find on
excellence in digital publishing. Reply with email subject “Subscribe to
Excellence” to join.

**Comment by swalkinshaw** [comment]
@MatthewEppelsheimer in the use case you explained you'd still need to make changes to your config and move the `canonical` element to the other env array. The solution I proposed would involve changing a conditional check from `production` to `staging` for example. It's basically the same amount of work.

I'm just hesitant to support this because I'd rather people not start adding a lot of other data to `ENVIRONMENTS`. Having to `serialize` is bad enough as it is.

**Comment by MatthewEppelsheimer** [comment]
Your hesitation makes sense and has spurred a lot more thinking that isn't worth going into here.

Let's close this. On my side, we need to get more clear on how best to solve our problem. Thank you for the discussion!
