### ISSUE TITLE
Doesn't work with Wordpress Multisite

### ISSUE THREAD

**Issue by richvida** [roots/wp-stage-switcher#8]
This is one of the coolest and most useful plugins I've come across in a while, however, it doesn't appear to have support for multisite setups.

From what I can tell, the `ENVIRONMENTS` constant doesn't let you define more than 1 site.

**Comment by retlehs** [comment]
https://github.com/roots/wp-stage-switcher/blob/ea612e414a3e814f1966c342ef34aee1ad6ef0ed/wp-stage-switcher.php#L58-L62
