### ISSUE TITLE
Install without composer?

### ISSUE THREAD

**Issue by joelworsham** [roots/wp-stage-switcher#9]
Is this possible? I want to use this on WP Engine, but WP Engine gives no ssh access. I need to be able to install it via SFTP. The issue is that this, of course, won't load dependencies and such properly.

**Comment by retlehs** [comment]
you can run `composer install` locally and then copy the contents of the directory up to the server. please use https://discourse.roots.io/ for support/questions

**Comment by joelworsham** [comment]
I didn't want to create an account to ask a question. Sorry for that. Thanks.
